# Assignment on Numpy

In [1]:
import numpy as np

## 1. Create a 1D array of numbers from 0 to 9.

In [2]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## 2. Create a 3×3 numpy array of all True’s

In [3]:
arr = np.ones((3,3),dtype = bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 3. Given an array as input, print only odd numbers as output

In [4]:
arr = np.arange(30)
arr[np.where( arr % 2 != 0)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## 4. Replace all odd numbers in arr with -2

In [5]:
arr = np.arange(30)
np.place(arr, arr % 2 != 0, -2)
arr

array([ 0, -2,  2, -2,  4, -2,  6, -2,  8, -2, 10, -2, 12, -2, 14, -2, 16,
       -2, 18, -2, 20, -2, 22, -2, 24, -2, 26, -2, 28, -2])

## 5. How to reshape an array?

In [6]:
arr = np.arange(100)
print(f"before reshaping :: \n{arr}")

arr = arr.reshape(10,10)
print(f"\nafter reshaping :: \n{arr}")

before reshaping :: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

after reshaping :: 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## 6. Convert a 1D array to a 2D array with 2 rows

In [7]:
# multiples of two's
arr =np.arange(16)
arr.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

## 7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9])

b= a[np.logical_or(a % 2 !=0,a %4 == 0)]
b.tolist()

[1, 3, 4, 5, 7, 8, 9]

## 8. Given array, check if there are any null values and print them out. 

In [9]:
x = np.array([[1,2,3,4],
              [2,3,np.nan,5],
              [np.nan,5,2,3]])

nanIndexes = np.where(np.isnan(x))
print(nanIndexes)
x[nanIndexes]

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))


array([nan, nan])

## 9. How to replace all missing values with 0 in a numpy array?

In [10]:
x = np.array([[1,2,3,4],
              [2,3,np.nan,5],
              [np.nan,5,2,3]])

np.place(x, np.isnan(x), 0)
x

array([[1., 2., 3., 4.],
       [2., 3., 0., 5.],
       [0., 5., 2., 3.]])

## 10. How to find the count of each unique number in a NumPy array?

In [11]:
x = np.array([1,2,3,4,5,6,7,8,9,6,4])

number,count = np.unique(x, return_counts=True)
uniques = number[np.where(count == 1)]
np.count_nonzero(uniques)

7

## 11. How to convert a numeric to a categorical (text) array?

In [12]:
import pandas as pd

x = pd.Series(np.arange(0,20), dtype="category")
x.dtype

CategoricalDtype(categories=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                  18, 19],
                 ordered=False)

## 12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 

In [13]:
a = np.arange(99,300)

multiple_of_5 = lambda x: x % 5 == 0
multiple_of_7 = lambda x: x % 7 == 0
multiple_of_7_and_5 = lambda x: multiple_of_5(x) & multiple_of_7(x)

a[(multiple_of_5(a) | multiple_of_7(a)) & ~(multiple_of_7_and_5(a))]

array([100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147,
       150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190,
       195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235,
       238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285,
       287, 290, 294, 295])

## 13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [14]:
x = np.array([1,2,3,4,5,6,7,8,9,6,4,8,8])

x[::-1]

array([8, 8, 4, 6, 9, 8, 7, 6, 5, 4, 3, 2, 1])